server:
  port: 8084
spring:
  application:
    name: mindmapservice
  jpa:
    database: "POSTGRESQL"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:7b

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5433/mindmapService
    username: root
    password: StrongP@ssword123

#  datasource:
#    driverClassName: "org.postgresql.Driver"
#    url: "jdbc:postgresql://localhost:5432/Mss-Mindmap"
#    username: "postgres"
#    password: "12345678"

#  datasource:
#    driverClassName: "org.postgresql.Driver"
#    url: "jdbc:postgresql://localhost:5432/test"
#    username: "postgres"
#    password: "12345"

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka

