server:
  port: 8084
spring:
  application:
    name: mindmapservice
  jpa:
    database: "POSTGRESQL"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update


  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/Mss-Mindmap"
    username: "postgres"
    password: "12345678"
#  datasource:
#    driverClassName: "org.postgresql.Driver"
#    url: "jdbc:postgresql://localhost:5432/test"
#    username: "postgres"
#    password: "12345"
eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
gateway:
  secret: 4391D97158194

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true


